name: unpub_auth
description: An auth tool for unpub.
version: 0.1.0+3
homepage: https://github.com/bytedance/unpub
resolution: workspace

environment:
  sdk: ^3.10.0

executables:
  unpub_auth:

dependencies:
  collection: ^1.19.0
  path: ^1.9.1
  http: ^1.2.2
  shelf: ^1.4.2
  http_multi_server: ^3.2.2
  oauth2: ^2.0.3
  args: ^2.7.0
  console: ^4.1.0

dev_dependencies:
  test: ^1.25.0
